name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Permet de lancer le build manuellement depuis l'interface

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v4

    - name: Configuration de Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Configuration de Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Génération du Wrapper Gradle
      run: gradle wrapper
      # Cette étape crée le fichier gradlew manquant

    - name: Rendre gradlew exécutable
      run: chmod +x ./gradlew
      # Cette étape donne les droits d'exécution au fichier fraîchement créé

    - name: Compilation de l'APK (Debug)
      run: ./gradlew assembleDebug
      # Cette étape compile votre application Kotlin

    - name: Upload de l'APK Debug
      uses: actions/upload-artifact@v4
      with:
          name: application-debug
          path: app/build/outputs/apk/debug/*.apk
      # Cette étape vous permet de télécharger l'APK à la fin du build
